### ISSUE TITLE
ImportError: No module named exceptions

### ISSUE THREAD

**Issue by peterwake** [phlax/xpootle.fs#20]
Hi there, I have been running pootle_fs_git successfully over the last couple of months. But just uninstalled and then reinstalled as follows:

```
pip uninstall pootle-fs-git
pip uninstall pootle-fs
pip uninstall pootle
pip install --upgrade pip setuptools
pip install --process-dependency-links --pre Pootle[git]
```

and get (along with a tonne of other info)

```
Installing collected packages: pootle-fs-git, Pootle
Running setup.py install for pootle-fs-git ... done
Running setup.py install for Pootle ... done
Successfully installed Pootle-2.8.0rc2 pootle-fs-git-0.0.1
```

But then when I try running

`pootle fs sync myrepo`

I get

```pytb
INFO Loading custom settings from '/root/.pootle/pootle.conf'...
Traceback (most recent call last):
  File "/var/www/pootle/env/bin/pootle", line 11, in <module>
    load_entry_point('Pootle==2.8.0rc2', 'console_scripts', 'pootle')()
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 315, in main
    django_settings_module='pootle.settings')
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 295, in run_app
    management.execute_from_command_line(command)
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle_fs_git/apps.py", line 20, in ready
    importlib.import_module("pootle_fs_git.providers")
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle_fs_git/providers.py", line 12, in <module>
    from .plugin import GitPlugin
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/pootle_fs_git/plugin.py", line 16, in <module>
    from pootle_fs.exceptions import FSFetchError
ImportError: No module named exceptions
```

Any suggestions much appreciated!

Thanks

**Comment by phlax** [comment]
hi @peterwake you will need the current pootle master to run the latest pootle_fs

**Comment by dwaynebailey** [comment]
@peterwake `pip install pootle[git]` should work now as the recent Pootle 2.8.0rc3 uses a specific commit of Pootle FS git.  If you're tracking `master` of Pootle FS git there might be other things broken at the moment.

**Comment by peterwake** [comment]
@phlax and @dwaynebailey thank you. I will retry the `pip install pootle[git]` later this week. Or should that be `pip install --process-dependency-links --pre pootle[git]`?

In general I find the install instructions are a bit skinny - I suspect this is because pootle_fs_git is at the 'bleeding edge'. Anyway I would say that with the un-updated version we have had great results, and love Pootle and pootle_fs_git.

The only problem we've had is that one language has got 'stuck' in limbo land. I think it is because one of our translators did some new translations in Pootle, and at the same time we also did a Git commit of new translations from our app, and so pootle_fs_git isn't able to resolve the conflict. However this is only a theory! And I am hoping the new version of pootle_fs_git might solve this.
